"""Generated by HYDRA - do not edit by hand.

    pipeline: fraud-detection
    backend:  kubeflow
    hydraml:  0.1.0

Regenerate with:
    hydraml compile <spec> --backend kubeflow
"""

from __future__ import annotations

from typing import NamedTuple

from kfp import dsl


@dsl.component(base_image='python:3.11')
def ingest_component(raw_path: str, sample_rows: int) -> str:
    from examples.fraud_detection.pipeline import ingest as _task_def

    return _task_def.fn(raw_path=raw_path, sample_rows=sample_rows)


@dsl.component(base_image='python:3.11')
def featurize_component(transactions_uri: str, window_days: int) -> str:
    from examples.fraud_detection.pipeline import featurize as _task_def

    return _task_def.fn(transactions_uri=transactions_uri, window_days=window_days)


@dsl.component(base_image='python:3.11')
def train_component(epochs: int, features_uri: str, learning_rate: float) -> NamedTuple("Outputs", [("model_uri", str), ("metrics", dict)]):
    from examples.fraud_detection.pipeline import train as _task_def

    result = _task_def.fn(epochs=epochs, features_uri=features_uri, learning_rate=learning_rate)
    from collections import namedtuple

    outputs = namedtuple("Outputs", ['model_uri', 'metrics'])
    return outputs(model_uri=result['model_uri'], metrics=result['metrics'])


@dsl.component(base_image='python:3.11')
def evaluate_component(features_uri: str, min_precision: float, model_uri: str) -> dict:
    from examples.fraud_detection.pipeline import evaluate as _task_def

    return _task_def.fn(features_uri=features_uri, min_precision=min_precision, model_uri=model_uri)


@dsl.pipeline(name='fraud-detection', description='Daily fraud-model training: ingest -> featurize -> train -> evaluate.')
def fraud_detection(raw_path: str = 's3://warehouse/transactions/', sample_rows: int = 500, window_days: int = 30, learning_rate: float = 0.01, epochs: int = 5, min_precision: float = 0.9):
    ingest_task = ingest_component(raw_path=raw_path, sample_rows=sample_rows)
    ingest_task.set_display_name('ingest')
    ingest_task.set_caching_options(False)
    ingest_task.set_retry(num_retries=2, backoff_duration='5s', backoff_factor=2.0)
    featurize_task = featurize_component(transactions_uri=ingest_task.output, window_days=window_days)
    featurize_task.set_display_name('featurize')
    featurize_task.set_caching_options(True)
    featurize_task.set_cpu_limit('2')
    featurize_task.set_memory_limit('4Gi')
    train_task = train_component(epochs=epochs, features_uri=featurize_task.output, learning_rate=learning_rate)
    train_task.set_display_name('train')
    train_task.set_caching_options(False)
    train_task.set_cpu_limit('4')
    train_task.set_memory_limit('8Gi')
    train_task.set_accelerator_type('NVIDIA_TESLA_T4')
    train_task.set_accelerator_limit(1)
    evaluate_task = evaluate_component(features_uri=featurize_task.output, min_precision=min_precision, model_uri=train_task.outputs['model_uri'])
    evaluate_task.set_display_name('evaluate')
    evaluate_task.set_caching_options(False)
    evaluate_task.set_retry(num_retries=1, backoff_duration='10s', backoff_factor=1.0)


if __name__ == "__main__":
    from kfp import compiler

    compiler.Compiler().compile(fraud_detection, package_path='fraud_detection.yaml')
