"""Generated by HYDRA - do not edit by hand.

    pipeline: fraud-detection
    backend:  airflow
    hydraml:  0.1.0

Regenerate with:
    hydraml compile <spec> --backend airflow

Parameters were bound at compile time:
    raw_path = 's3://warehouse/transactions/'
    sample_rows = 500
    window_days = 30
    learning_rate = 0.01
    epochs = 5
    min_precision = 0.9
"""

from __future__ import annotations

from datetime import datetime, timedelta

from airflow.decorators import dag, task

from examples.fraud_detection.pipeline import ingest as _hydra_ingest
from examples.fraud_detection.pipeline import featurize as _hydra_featurize
from examples.fraud_detection.pipeline import train as _hydra_train
from examples.fraud_detection.pipeline import evaluate as _hydra_evaluate


@dag(
    dag_id='fraud_detection',
    description='Daily fraud-model training: ingest -> featurize -> train -> evaluate.',
    schedule='0 6 * * *',
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=['fraud', 'hydra', 'ml'],
)
def fraud_detection():
    @task(task_id='ingest', retries=2, retry_delay=timedelta(seconds=5.0), retry_exponential_backoff=True)
    def ingest(raw_path, sample_rows):
        return _hydra_ingest.fn(raw_path=raw_path, sample_rows=sample_rows)

    @task(task_id='featurize', executor_config={'pod_override': {'spec': {'containers': [{'name': 'base', 'resources': {'requests': {'cpu': '2', 'memory': '4Gi'}, 'limits': {'cpu': '2', 'memory': '4Gi'}}}]}}})
    def featurize(transactions_uri, window_days):
        return _hydra_featurize.fn(transactions_uri=transactions_uri, window_days=window_days)

    @task(task_id='train', multiple_outputs=True, executor_config={'pod_override': {'spec': {'containers': [{'name': 'base', 'resources': {'requests': {'cpu': '4', 'memory': '8Gi', 'nvidia.com/gpu': '1'}, 'limits': {'cpu': '4', 'memory': '8Gi', 'nvidia.com/gpu': '1'}}}]}}})
    def train(epochs, features_uri, learning_rate):
        result = _hydra_train.fn(epochs=epochs, features_uri=features_uri, learning_rate=learning_rate)
        return {key: result[key] for key in ['model_uri', 'metrics']}

    @task(task_id='evaluate', retries=1, retry_delay=timedelta(seconds=10.0))
    def evaluate(features_uri, min_precision, model_uri):
        return _hydra_evaluate.fn(features_uri=features_uri, min_precision=min_precision, model_uri=model_uri)

    ingest_result = ingest(raw_path='s3://warehouse/transactions/', sample_rows=500)
    featurize_result = featurize(transactions_uri=ingest_result, window_days=30)
    train_result = train(epochs=5, features_uri=featurize_result, learning_rate=0.01)
    evaluate_result = evaluate(features_uri=featurize_result, min_precision=0.9, model_uri=train_result['model_uri'])


fraud_detection()
