"""Generated by HYDRA - do not edit by hand.

    pipeline: fraud-detection
    backend:  prefect
    hydraml:  0.1.0

Regenerate with:
    hydraml compile <spec> --backend prefect
"""

from __future__ import annotations

from prefect import flow, task
from prefect.cache_policies import INPUTS

from examples.fraud_detection.pipeline import ingest as _hydra_ingest
from examples.fraud_detection.pipeline import featurize as _hydra_featurize
from examples.fraud_detection.pipeline import train as _hydra_train
from examples.fraud_detection.pipeline import evaluate as _hydra_evaluate


ingest = task(name='ingest', retries=2, retry_delay_seconds=[5.0, 10.0])(_hydra_ingest.fn)

featurize = task(name='featurize', cache_policy=INPUTS, tags=['cpu:2', 'memory:4Gi'])(_hydra_featurize.fn)

train = task(name='train', tags=['cpu:4', 'memory:8Gi', 'gpu:1'])(_hydra_train.fn)

evaluate = task(name='evaluate', retries=1, retry_delay_seconds=10.0)(_hydra_evaluate.fn)


@flow(name='fraud-detection', description='Daily fraud-model training: ingest -> featurize -> train -> evaluate.')
def fraud_detection(raw_path: str = 's3://warehouse/transactions/', sample_rows: int = 500, window_days: int = 30, learning_rate: float = 0.01, epochs: int = 5, min_precision: float = 0.9):
    ingest_result = ingest(raw_path=raw_path, sample_rows=sample_rows)
    featurize_result = featurize(transactions_uri=ingest_result, window_days=window_days)
    train_result = train(epochs=epochs, features_uri=featurize_result, learning_rate=learning_rate)
    evaluate_result = evaluate(features_uri=featurize_result, min_precision=min_precision, model_uri=train_result['model_uri'])
    return evaluate_result


if __name__ == "__main__":
    fraud_detection.serve(name='fraud-detection', cron='0 6 * * *')
