"""Shared helpers for the code-generating backends.

HYDRA generates *source code* in each orchestrator's native idiom rather than
wrapping orchestrators at run time. The generated file is plain, reviewable
Python with no hydraml import requirement beyond the user's own task module -
so the artifact can be committed, diffed, and deployed like any hand-written
DAG/flow/pipeline.
"""

from __future__ import annotations

import re

from .. import __version__
from ..ir.model import (
    InputValue,
    LiteralValue,
    OutputRef,
    ParamRef,
    Pipeline,
    TaskSpec,
)

_IDENT_RE = re.compile(r"[^0-9a-zA-Z_]")


def sanitize(name: str) -> str:
    """Coerce an IR name into a valid Python identifier."""
    ident = _IDENT_RE.sub("_", name)
    if not ident or ident[0].isdigit():
        ident = "_" + ident
    return ident


def header(pipeline: Pipeline, backend: str, extra: list[str] | None = None) -> list[str]:
    lines = [
        '"""Generated by HYDRA - do not edit by hand.',
        "",
        f"    pipeline: {pipeline.name}",
        f"    backend:  {backend}",
        f"    hydraml:  {__version__}",
        "",
        "Regenerate with:",
        f"    hydraml compile <spec> --backend {backend}",
    ]
    if extra:
        lines.append("")
        lines.extend(extra)
    lines.append('"""')
    return lines


class Emitter:
    """Tiny indentation-aware line buffer."""

    def __init__(self) -> None:
        self._lines: list[str] = []
        self._indent = 0

    def line(self, text: str = "") -> None:
        self._lines.append(("    " * self._indent + text) if text else "")

    def lines(self, texts: list[str]) -> None:
        for text in texts:
            self.line(text)

    def blank(self, count: int = 1) -> None:
        self._lines.extend([""] * count)

    def indent(self) -> None:
        self._indent += 1

    def dedent(self) -> None:
        self._indent -= 1

    def source(self) -> str:
        return "\n".join(self._lines).rstrip() + "\n"


def import_aliases(pipeline: Pipeline) -> dict[str, tuple[str, str, str]]:
    """Map each distinct fn_ref to (module, attr, alias) for import statements."""
    aliases: dict[str, tuple[str, str, str]] = {}
    used: set[str] = set()
    for task in pipeline.tasks.values():
        if task.fn_ref in aliases:
            continue
        module, _, attr = task.fn_ref.partition(":")
        alias = f"_hydra_{sanitize(attr)}"
        while alias in used:
            alias += "_"
        used.add(alias)
        aliases[task.fn_ref] = (module, attr, alias)
    return aliases


def result_var(task_name: str) -> str:
    return f"{sanitize(task_name)}_result"


def render_input(
    value: InputValue,
    params: dict[str, object],
    upstream: dict[str, TaskSpec],
    *,
    runtime_params: bool,
    output_expr,
) -> str:
    """Render one task-call argument as a Python expression.

    ``output_expr(ref, upstream_task)`` renders a reference to an upstream
    result in the backend's idiom. When ``runtime_params`` is false, params
    are folded to their resolved compile-time values.
    """
    if isinstance(value, LiteralValue):
        return repr(value.value)
    if isinstance(value, ParamRef):
        return value.param if runtime_params else repr(params[value.param])
    if isinstance(value, OutputRef):
        return output_expr(value, upstream[value.task])
    raise TypeError(f"unexpected input value: {value!r}")
